var CAREER_ECOSYSTEM_DATA = {
  gyms: [
    { id: "mexico_barrio_pit", country: "mexico", city: "Мехико", name: "Barrio Pit", cost: 18, specialization: "Корпус и давление", reputation: 42, bonuses: { trainingPoints: 2, safeBias: 1, dangerBias: 1 }, trainerTypeIds: ["body_lab", "conditioning"], description: "Жёсткий недорогой зал, где любят рубку и постоянный прессинг." },
    { id: "mexico_norte_boxing", country: "mexico", city: "Монтеррей", name: "Norte Boxing House", cost: 24, specialization: "Темп и силовой размен", reputation: 55, bonuses: { trainingPoints: 1, purseBonus: 8, homeBias: 1 }, trainerTypeIds: ["old_school", "finisher"], description: "Более статусная база с плотным соревновательным режимом." },
    { id: "usa_vegas_workshop", country: "usa", city: "Лас-Вегас", name: "Vegas Workshop", cost: 32, specialization: "Афиша и темп", reputation: 68, bonuses: { purseBonus: 18, fameBonus: 2, awayBias: 1 }, trainerTypeIds: ["media_operator", "sharp_technician"], description: "Зал со связями, где любят продаваемые бои и громкие имена." },
    { id: "usa_brooklyn_grind", country: "usa", city: "Нью-Йорк", name: "Brooklyn Grind Gym", cost: 22, specialization: "База и объём", reputation: 51, bonuses: { trainingPoints: 2, safeBias: 1, recoveryHealth: 2 }, trainerTypeIds: ["conditioning", "old_school"], description: "Крепкая рабочая база без лишнего блеска." },
    { id: "russia_yard_team", country: "russia", city: "Москва", name: "Команда Дворового Ринга", cost: 16, specialization: "Жёсткая база", reputation: 44, bonuses: { trainingPoints: 2, toxicGuard: 6, safeBias: 1 }, trainerTypeIds: ["old_school", "conditioning"], description: "Суровая школа, где сначала требуют характер, а потом талант." },
    { id: "russia_neva_line", country: "russia", city: "Санкт-Петербург", name: "Neva Line", cost: 26, specialization: "Контратака и тайминг", reputation: 60, bonuses: { trainingPoints: 1, fameBonus: 1, safeBias: 2 }, trainerTypeIds: ["sharp_technician", "old_school"], description: "Собранный зал с акцентом на дисциплину и выверенный темп." },
    { id: "cuba_malecon_school", country: "cuba", city: "Гавана", name: "Malecon School", cost: 20, specialization: "Ноги и защита", reputation: 58, bonuses: { recoveryHealth: 3, safeBias: 2, trainingPoints: 1 }, trainerTypeIds: ["sharp_technician", "conditioning"], description: "Школа ритма и скольжения с сильной базой восстановления." },
    { id: "cuba_santiago_rhythm", country: "cuba", city: "Сантьяго-де-Куба", name: "Santiago Rhythm Hall", cost: 18, specialization: "Ритм и мотор", reputation: 49, bonuses: { trainingPoints: 2, awayBias: 1, fameBonus: 1 }, trainerTypeIds: ["conditioning", "media_operator"], description: "Легче по деньгам, но даёт хороший мотор и уверенность." },
    { id: "japan_tokyo_discipline", country: "japan", city: "Токио", name: "Tokyo Discipline Club", cost: 30, specialization: "Точность и порядок", reputation: 66, bonuses: { trainingPoints: 2, toxicGuard: 8, safeBias: 2 }, trainerTypeIds: ["sharp_technician", "old_school"], description: "Дорогой, но очень надёжный зал с высокой дисциплиной." },
    { id: "japan_osaka_smoke", country: "japan", city: "Осака", name: "Osaka Smoke Works", cost: 24, specialization: "Темп и выверенный вход", reputation: 53, bonuses: { trainingPoints: 1, purseBonus: 6, fameBonus: 1 }, trainerTypeIds: ["sharp_technician", "media_operator"], description: "Сочетает строгую школу и аккуратную медийность." },
    { id: "china_shanghai_engine", country: "china", city: "Шанхай", name: "Shanghai Engine", cost: 28, specialization: "Дистанция и серия", reputation: 61, bonuses: { trainingPoints: 2, awayBias: 1, purseBonus: 7 }, trainerTypeIds: ["sharp_technician", "conditioning"], description: "Хороший баланс техники и рабочего темпа." },
    { id: "china_beijing_iron", country: "china", city: "Пекин", name: "Beijing Iron Works", cost: 21, specialization: "Терпение и силовой тайминг", reputation: 50, bonuses: { safeBias: 1, dangerBias: 1, recoveryHealth: 2 }, trainerTypeIds: ["old_school", "finisher"], description: "Зал для тех, кто умеет терпеть ради позднего взрыва." },
    { id: "uk_london_cellar", country: "uk", city: "Лондон", name: "London Cellar", cost: 27, specialization: "Классика и джеб", reputation: 63, bonuses: { trainingPoints: 1, safeBias: 2, purseBonus: 6 }, trainerTypeIds: ["sharp_technician", "old_school"], description: "Классическая база с уважением к рисунку боя." },
    { id: "uk_manchester_brick", country: "uk", city: "Манчестер", name: "Manchester Brick Gym", cost: 19, specialization: "Работа на характере", reputation: 47, bonuses: { trainingPoints: 2, toxicGuard: 4, homeBias: 1 }, trainerTypeIds: ["conditioning", "old_school"], description: "Грубоватый, но честный зал для тяжёлой работы." },
    { id: "philippines_manila_motor", country: "philippines", city: "Манила", name: "Manila Motor House", cost: 20, specialization: "Мотор и объём", reputation: 57, bonuses: { trainingPoints: 2, awayBias: 1, fameBonus: 1 }, trainerTypeIds: ["conditioning", "finisher"], description: "Зал высокого темпа, где любят задавливать объёмом." },
    { id: "philippines_cebu_storm", country: "philippines", city: "Себу", name: "Cebu Storm Camp", cost: 17, specialization: "Давление и темп", reputation: 46, bonuses: { trainingPoints: 1, dangerBias: 2, purseBonus: 4 }, trainerTypeIds: ["finisher", "conditioning"], description: "Дешевле и жёстче, чем выглядит снаружи." }
  ],
  trainerTypes: [
    { id: "old_school", label: "Старая школа", weeklyFee: 24, specialization: "База, дисциплина и безопасные решения", reputation: 58, bonuses: { trainingPoints: 3, safeBias: 2, toxicGuard: 8, recoveryHealth: 1 }, description: "Строит фундамент и режет лишний хаос." },
    { id: "conditioning", label: "Физподготовка", weeklyFee: 18, specialization: "Выносливость, режим и восстановление", reputation: 49, bonuses: { trainingPoints: 2, recoveryHealth: 4, stressRelief: 2, safeBias: 1 }, description: "Даёт больше ресурса на длинной дистанции, но без особого блеска." },
    { id: "sharp_technician", label: "Технарь", weeklyFee: 30, specialization: "Тайминг, дистанция и качество решений", reputation: 64, bonuses: { trainingPoints: 3, purseBonus: 8, safeBias: 1, fameBonus: 1 }, description: "Подтягивает рисунок боя и делает лагерь умнее." },
    { id: "finisher", label: "Финишёр", weeklyFee: 26, specialization: "Жёсткий темп и концовки", reputation: 52, bonuses: { dangerBias: 2, koBonus: 20, purseBonus: 4, trainingPoints: 1 }, description: "Любит риск ради громких завершений." },
    { id: "media_operator", label: "Медийный тренер", weeklyFee: 34, specialization: "Продажа имени и связи", reputation: 61, bonuses: { fameBonus: 3, purseBonus: 12, awayBias: 1, toxicGuard: -8 }, description: "Делает имя громче, но иногда тянет в мутные условия." },
    { id: "body_lab", label: "Корпусной мастер", weeklyFee: 22, specialization: "Работа по корпусу и давление", reputation: 51, bonuses: { trainingPoints: 2, dangerBias: 1, recoveryHealth: 1 }, description: "Собирает тяжёлый ближний бой и методично сушит соперника." }
  ],
  contractTemplates: [
    { id: "local_handshake", label: "Локальный рукопожатный", durationWeeks: 6, guaranteedPurse: 85, winBonus: 35, koBonus: 20, fameMultiplier: 1.0, fightFrequency: 1, toxicRisk: 8, conditionsText: "Домашние вечера, спокойный матчмейкинг и минимум сюрпризов.", reputationDelta: 1, description: "Самый безопасный способ закрепиться на местной сцене." },
    { id: "road_grinder", label: "Дорожный контракт", durationWeeks: 7, guaranteedPurse: 105, winBonus: 45, koBonus: 30, fameMultiplier: 1.1, fightFrequency: 2, toxicRisk: 16, conditionsText: "Поездки, короткие лагеря и жёсткий график.", reputationDelta: 2, description: "Денег больше, но придётся жить между перелётами." },
    { id: "spotlight_push", label: "Пуш в афишу", durationWeeks: 8, guaranteedPurse: 125, winBonus: 60, koBonus: 45, fameMultiplier: 1.25, fightFrequency: 2, toxicRisk: 28, conditionsText: "Ставка на имя, интервью и давление результата.", reputationDelta: 4, description: "Больше известности и денег, но выше ожидания." },
    { id: "shark_clause", label: "Акулья сделка", durationWeeks: 8, guaranteedPurse: 155, winBonus: 75, koBonus: 60, fameMultiplier: 1.15, fightFrequency: 3, toxicRisk: 46, conditionsText: "Крупные деньги, короткие сроки и грязные оговорки мелким шрифтом.", reputationDelta: 3, description: "Очень выгодно на бумаге и очень нервно в реальности." }
  ],
  fightOfferTemplates: [
    { id: "home_safe", label: "Домашний безопасный бой", travel: "home", tier: "safe", description: "Свой зал, удобная логистика и осторожный соперник.", purseBase: 70, winBonus: 20, koBonus: 20, fameBase: 6, toxicBase: 6, declineRep: 0, acceptRep: 1 },
    { id: "home_even", label: "Домашний равный бой", travel: "home", tier: "even", description: "Свой город, но без подарков по уровню.", purseBase: 95, winBonus: 30, koBonus: 28, fameBase: 10, toxicBase: 10, declineRep: -1, acceptRep: 2 },
    { id: "home_danger", label: "Домашний опасный бой", travel: "home", tier: "danger", description: "Громкий вечер дома против серьёзного имени.", purseBase: 120, winBonus: 40, koBonus: 36, fameBase: 15, toxicBase: 14, declineRep: -1, acceptRep: 3 },
    { id: "away_safe", label: "Выездной удобный бой", travel: "away", tier: "safe", description: "Чужая арена, но соперник по силам.", purseBase: 85, winBonus: 25, koBonus: 25, fameBase: 9, toxicBase: 12, declineRep: -1, acceptRep: 2 },
    { id: "away_even", label: "Выездной равный бой", travel: "away", tier: "even", description: "Нормальный выездной матч с честным риском.", purseBase: 110, winBonus: 35, koBonus: 32, fameBase: 14, toxicBase: 18, declineRep: -2, acceptRep: 3 },
    { id: "away_danger", label: "Выездной опасный бой", travel: "away", tier: "danger", description: "Чужая территория и высокий риск ради рывка.", purseBase: 145, winBonus: 45, koBonus: 45, fameBase: 19, toxicBase: 24, declineRep: -2, acceptRep: 4 },
    { id: "rematch_offer", label: "Реванш", travel: "rematch", tier: "even", description: "История ещё не закрыта. Рынок любит вторую серию.", purseBase: 125, winBonus: 40, koBonus: 35, fameBase: 16, toxicBase: 16, declineRep: -3, acceptRep: 4 }
  ]
};
