var CAREER_ECOSYSTEM_DATA = {
  gyms: [
    { id: "mexico_barrio_pit", country: "mexico", city: "Мехико", name: "Barrio Pit", cost: 18, specialization: "рубка и корпус", reputation: 42, bonuses: { trainingPoints: 2, safeBias: 1, dangerBias: 1 }, trainerTypeIds: ["body_lab", "conditioning"], description: "Жаркий тесный зал, где бойца учат ломать темп через давление и тело." },
    { id: "mexico_norte_boxing", country: "mexico", city: "Монтеррей", name: "Norte Boxing House", cost: 24, specialization: "мощь и жёсткие серии", reputation: 55, bonuses: { trainingPoints: 1, purseBonus: 8, homeBias: 1 }, trainerTypeIds: ["old_school", "finisher"], description: "Северная школа, где любят тяжёлые руки и короткие размены." },

    { id: "usa_vegas_workshop", country: "usa", city: "Лас-Вегас", name: "Vegas Workshop", cost: 32, specialization: "контракт и витрина", reputation: 68, bonuses: { purseBonus: 18, fameBonus: 2, awayBias: 1 }, trainerTypeIds: ["media_operator", "sharp_technician"], description: "Зал, который помогает не только тренироваться, но и выгодно выглядеть на рынке." },
    { id: "usa_brooklyn_grind", country: "usa", city: "Нью-Йорк", name: "Brooklyn Grind Gym", cost: 22, specialization: "грязная работа и объём", reputation: 51, bonuses: { trainingPoints: 2, safeBias: 1, recoveryHealth: 2 }, trainerTypeIds: ["conditioning", "old_school"], description: "Старый зал, где бойцов строят через объём, пот и привычку не ломаться." },

    { id: "russia_yard_team", country: "russia", city: "Москва", name: "Дворовая сборная", cost: 16, specialization: "жёсткая база", reputation: 44, bonuses: { trainingPoints: 2, toxicGuard: 6, safeBias: 1 }, trainerTypeIds: ["old_school", "conditioning"], description: "Место для тех, кто привык вывозить характером и силовой дисциплиной." },
    { id: "russia_neva_line", country: "russia", city: "Санкт-Петербург", name: "Neva Line", cost: 26, specialization: "дистанция и холодная голова", reputation: 60, bonuses: { trainingPoints: 1, fameBonus: 1, safeBias: 2 }, trainerTypeIds: ["sharp_technician", "old_school"], description: "Школа терпения, точного шага и аккуратной работы на ошибке." },

    { id: "cuba_malecon_school", country: "cuba", city: "Гавана", name: "Malecon School", cost: 20, specialization: "ноги и ритм", reputation: 58, bonuses: { recoveryHealth: 3, safeBias: 2, trainingPoints: 1 }, trainerTypeIds: ["sharp_technician", "conditioning"], description: "Лагерь лёгких ног, чистого ритма и красивой дистанционной работы." },
    { id: "cuba_santiago_rhythm", country: "cuba", city: "Сантьяго-де-Куба", name: "Santiago Rhythm Hall", cost: 18, specialization: "ритм и объём", reputation: 49, bonuses: { trainingPoints: 2, awayBias: 1, fameBonus: 1 }, trainerTypeIds: ["conditioning", "media_operator"], description: "Школа движения и темпа, где бойца учат дышать боем." },

    { id: "japan_tokyo_discipline", country: "japan", city: "Токио", name: "Tokyo Discipline Club", cost: 30, specialization: "точность и режим", reputation: 66, bonuses: { trainingPoints: 2, toxicGuard: 8, safeBias: 2 }, trainerTypeIds: ["sharp_technician", "old_school"], description: "Лагерь порядка, в котором техника важнее шума." },
    { id: "japan_osaka_smoke", country: "japan", city: "Осака", name: "Osaka Smoke Works", cost: 24, specialization: "техника под давлением", reputation: 53, bonuses: { trainingPoints: 1, purseBonus: 6, fameBonus: 1 }, trainerTypeIds: ["sharp_technician", "media_operator"], description: "Современная школа под рынок, но с жёсткой работой по качеству движений." },

    { id: "china_shanghai_engine", country: "china", city: "Шанхай", name: "Shanghai Engine", cost: 28, specialization: "объём и мотор", reputation: 61, bonuses: { trainingPoints: 2, awayBias: 1, purseBonus: 7 }, trainerTypeIds: ["sharp_technician", "conditioning"], description: "Системный зал, где лагерь строят вокруг длинной дистанции и формы." },
    { id: "china_beijing_iron", country: "china", city: "Пекин", name: "Beijing Iron Works", cost: 21, specialization: "жёсткая защита", reputation: 50, bonuses: { safeBias: 1, dangerBias: 1, recoveryHealth: 2 }, trainerTypeIds: ["old_school", "finisher"], description: "Там, где защиту и плотность ставят выше показного блеска." },

    { id: "uk_london_cellar", country: "uk", city: "Лондон", name: "London Cellar", cost: 27, specialization: "джеб и шаг", reputation: 63, bonuses: { trainingPoints: 1, safeBias: 2, purseBonus: 6 }, trainerTypeIds: ["sharp_technician", "old_school"], description: "Классическая британская школа с акцентом на контроль боя через джеб." },
    { id: "uk_manchester_brick", country: "uk", city: "Манчестер", name: "Manchester Brick Gym", cost: 19, specialization: "выносливость и характер", reputation: 47, bonuses: { trainingPoints: 2, toxicGuard: 4, homeBias: 1 }, trainerTypeIds: ["conditioning", "old_school"], description: "Зал, который лепит не глянец, а бойца, способного тянуть тяжёлую неделю." },

    { id: "philippines_manila_motor", country: "philippines", city: "Манила", name: "Manila Motor House", cost: 20, specialization: "темп и серия", reputation: 57, bonuses: { trainingPoints: 2, awayBias: 1, fameBonus: 1 }, trainerTypeIds: ["conditioning", "finisher"], description: "Место, где бойцу ставят мотор и привычку навязывать ритм." },
    { id: "philippines_cebu_storm", country: "philippines", city: "Себу", name: "Cebu Storm Camp", cost: 17, specialization: "жёсткий спарринг", reputation: 46, bonuses: { trainingPoints: 1, dangerBias: 2, purseBonus: 4 }, trainerTypeIds: ["finisher", "conditioning"], description: "Лагерь, где темп и жёсткость приходят через тяжёлые раунды." }
  ],

  trainerTypes: [
    { id: "old_school", label: "Старая школа", weeklyFee: 24, specialization: "база, дисциплина и терпение", reputation: 58, bonuses: { trainingPoints: 3, safeBias: 2, toxicGuard: 8, recoveryHealth: 1 }, description: "Ставит фундамент и не любит суету вокруг лагеря." },
    { id: "conditioning", label: "Физподготовка", weeklyFee: 18, specialization: "выносливость, мотор и режим", reputation: 49, bonuses: { trainingPoints: 2, recoveryHealth: 4, stressRelief: 2, safeBias: 1 }, description: "Строит тело и дыхание, чтобы ты не рассыпался к середине боя." },
    { id: "sharp_technician", label: "Технарь", weeklyFee: 30, specialization: "точность, тайминг и сборка боя", reputation: 64, bonuses: { trainingPoints: 3, purseBonus: 8, safeBias: 1, fameBonus: 1 }, description: "Разбирает бой на детали и заставляет работать их под тебя." },
    { id: "finisher", label: "Финишёр", weeklyFee: 26, specialization: "мощь и концовка", reputation: 52, bonuses: { dangerBias: 2, koBonus: 20, purseBonus: 4, trainingPoints: 1 }, description: "Любит, когда бой заканчивается до гонга, а не после подсчёта судей." },
    { id: "media_operator", label: "Медийный тренер", weeklyFee: 34, specialization: "витрина, шум и рынок", reputation: 61, bonuses: { fameBonus: 3, purseBonus: 12, awayBias: 1, toxicGuard: -8 }, description: "Помогает строить имя, но часто приводит с ним и лишние риски." },
    { id: "body_lab", label: "Лаборатория корпуса", weeklyFee: 22, specialization: "корпус и плотная ближняя работа", reputation: 51, bonuses: { trainingPoints: 2, dangerBias: 1, recoveryHealth: 1 }, description: "Ставит давление через корпус, ритм и тяжёлую работу в тесной дистанции." }
  ],

  contractTemplates: [
    { id: "local_handshake", label: "Локальное соглашение", durationWeeks: 6, guaranteedPurse: 85, winBonus: 35, koBonus: 20, fameMultiplier: 1.0, fightFrequency: 1, toxicRisk: 8, conditionsText: "Спокойный контракт, простые условия и понятная дорожка боёв.", reputationDelta: 1, description: "Первый рабочий контракт без большого шума и тяжёлых пунктов." },
    { id: "road_grinder", label: "Гастрольный контракт", durationWeeks: 7, guaranteedPurse: 105, winBonus: 45, koBonus: 30, fameMultiplier: 1.1, fightFrequency: 2, toxicRisk: 16, conditionsText: "Больше выездов, больше логистики и выше требования к темпу карьеры.", reputationDelta: 2, description: "Больше движения и денег, но рынок начнёт требовать от тебя стабильности." },
    { id: "spotlight_push", label: "Толчок в витрину", durationWeeks: 8, guaranteedPurse: 125, winBonus: 60, koBonus: 45, fameMultiplier: 1.25, fightFrequency: 2, toxicRisk: 28, conditionsText: "Больше внимания, больше давления и меньше права на тихую неделю.", reputationDelta: 4, description: "Контракт для тех, кого начинают вытаскивать на свет." },
    { id: "shark_clause", label: "Акулий пункт", durationWeeks: 8, guaranteedPurse: 155, winBonus: 75, koBonus: 60, fameMultiplier: 1.15, fightFrequency: 3, toxicRisk: 46, conditionsText: "Жёсткие обязательства, плотный график и пункты, которые могут больно ударить по карьере.", reputationDelta: 3, description: "Большие деньги и опасные формулировки — хороший тест на дисциплину и команду." }
  ],

  fightOfferTemplates: [
    { id: "home_safe", label: "Домашний безопасный бой", travel: "home", tier: "safe", description: "Бой дома против понятного соперника с низким риском.", purseBase: 70, winBonus: 20, koBonus: 20, fameBase: 6, toxicBase: 6, declineRep: 0, acceptRep: 1 },
    { id: "home_even", label: "Домашний ровный бой", travel: "home", tier: "even", description: "Нормальная домашняя проверка без лишней страховки.", purseBase: 95, winBonus: 30, koBonus: 28, fameBase: 10, toxicBase: 10, declineRep: -1, acceptRep: 2 },
    { id: "home_danger", label: "Домашний опасный бой", travel: "home", tier: "danger", description: "Бой при своей публике, но с соперником, который может всё испортить.", purseBase: 120, winBonus: 40, koBonus: 36, fameBase: 15, toxicBase: 14, declineRep: -1, acceptRep: 3 },
    { id: "away_safe", label: "Выездной осторожный бой", travel: "away", tier: "safe", description: "Поездка ради имени и практики, без максимального риска.", purseBase: 85, winBonus: 25, koBonus: 25, fameBase: 9, toxicBase: 12, declineRep: -1, acceptRep: 2 },
    { id: "away_even", label: "Выездной ровный бой", travel: "away", tier: "even", description: "Полноценная проверка на чужой территории.", purseBase: 110, winBonus: 35, koBonus: 32, fameBase: 14, toxicBase: 18, declineRep: -2, acceptRep: 3 },
    { id: "away_danger", label: "Выездной рискованный бой", travel: "away", tier: "danger", description: "Шанс быстро поднять имя, но цена ошибки будет выше обычного.", purseBase: 145, winBonus: 45, koBonus: 45, fameBase: 19, toxicBase: 24, declineRep: -2, acceptRep: 4 },
    { id: "rematch_offer", label: "Реванш", travel: "rematch", tier: "even", description: "Прошлый бой не закрыл вопрос. Значит, рынок хочет увидеть ещё один ответ.", purseBase: 125, winBonus: 40, koBonus: 35, fameBase: 16, toxicBase: 16, declineRep: -3, acceptRep: 4 }
  ]
};
